language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk7

before_script:
  - mysql -e 'create database valamis_test;'
  - psql -c 'create database valamis_test;' -U postgres

script: sbt portlet/compile
